### ISSUE TITLE
alignRBR: Dimensions of matrices being concatenated are not consistent error

### ISSUE THREAD

**Issue by tayden** [mhalvers/RBRproc#1]
Getting a `Dimensions of matrices being concatenated are not consistent.` error when processing data through the alignRBR.m module if the variable being aligned is a row vector instead of a column vector. The other modules seem to work with row vectors.

This can be fixed by changing [Line 49](https://github.com/mhalvers/RBRproc/blob/master/alignRBR.m#L49) to `out.(vars{k}) = cat(2,NaN(1,nscan),in.(vars{k})(1:end-nscan));` and [Line 53](https://github.com/mhalvers/RBRproc/blob/master/alignRBR.m#L53) to `out.(vars{k}) = cat(2,in.(vars{k})(nscan+1:end),NaN(1,nscan));`

Is it the intended behaviour that all data being passed into alignRBR as the vars parameter are column vectors? I admit that I'm trying to mock the structure output by rbrExtractVals.m since the data I'm processing is from a database table, not an .rsk file.

**Comment by tayden** [comment]
The output of rbrExtractVals produces row vectors, so I'm assuming this is the expected input and closing the issue.

**Comment by mhalvers** [comment]
I prefer to work with column vectors, but honestly I hadn't made any intentional choices here.  The row vectors are inherited from the structure output by `RSKreaddata.m` in [rsktools](https://bitbucket.org/rbr/rsktools).
