### ISSUE TITLE
binRBR: variable "unit" not defined when binning by pressure

### ISSUE THREAD

**Issue by tayden** [mhalvers/RBRproc#3]
The binRBR.m module throws an error if binning by pressure because the variable "unit" is never defined. When binning by depth, the variable is initialized at [line 53](https://github.com/mhalvers/RBRproc/blob/master/binRBR.m#L53).

[This line](https://github.com/mhalvers/RBRproc/blob/master/binRBR.m#L87) is where the error occurs.

**Comment by tayden** [comment]
Fixed in https://github.com/mhalvers/RBRproc/pull/4

**Comment by mhalvers** [comment]
I merged the changes.  Thanks!
